name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Tests
        run: |
          robot tests/

      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: |
            log.html
            report.html
            output.xml

  download:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Robot Results
        uses: actions/download-artifact@v4
        with:
          name: robot-report
          path: ./downloads

      - name: Display downloaded files
        run: |
          echo "Downloaded files:"
          ls ./downloads
