name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Tests
        run: |
          robot tests/  # Ensure tests are running and output files are generated

      - name: Upload Robot Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-report  # Artifact name (This name must match the one in download step)
          path: |
            log.html
            report.html
            output.xml

  download:
    runs-on: ubuntu-latest
    needs: test  # This ensures the `download` job runs after the `test` job completes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Robot Results
        uses: actions/download-artifact@v3
        with:
          name: robot-report  # Same name used in the upload step
          path: ./downloads  # Folder where the artifact will be downloaded

      - name: Display downloaded files
        run: |
          echo "Downloaded files:"
          ls ./downloads  # List the downloaded files to verify
